#!/usr/bin/env bash

podman run \
	--rm \
	--userns keep-id \
	--device /dev/fuse \
	--security-opt label=disable \
	-v "$PWD":/home/podman/mnt:Z \
	-v ~/.config/git:/home/podman/.config/git:ro,z \
	-v ~/.cache/pre-commit:/home/podman/.cache/pre-commit:Z \
	-v "$HOME/.gnupg":/home/podman/.gnupg:ro,z \
	-v "$HOME/.ssh":/home/podman/.ssh:ro,z \
	-v "$XDG_RUNTIME_DIR/gnupg/S.gpg-agent":/home/podman/.gnupg/S.gpg-agent \
	-v "$SSH_AUTH_SOCK":"$SSH_AUTH_SOCK" \
	-e SSH_AUTH_SOCK="$SSH_AUTH_SOCK" \
	-v pre-commit:/home/podman/.local/share/containers/storage \
	--name pre-commit \
	quay.io/jwillikers/pre-commit \
	git "$@"
